import { lstat, mkdir, symlink, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import type { SpoolConfig } from "../../config.ts";
import type { PassageLocationMap } from "./reference-map.ts";

// Spool's own node_modules directory. Projects using spool typically have no
// VitePress/Vue of their own, so we symlink .site/node_modules to spool's copy
// so that VitePress can resolve its dependencies.
//
// Path from source: src/commands/site/vitepress.ts → 4 dirname calls → spool/
// Path from dist:   dist/commands/site/vitepress.js → 4 dirname calls → spool/
const SPOOL_ROOT = dirname(dirname(dirname(dirname(fileURLToPath(import.meta.url)))));
const SPOOL_NODE_MODULES = join(SPOOL_ROOT, "node_modules");

export async function prepareSiteDir(projectRoot: string): Promise<void> {
  const siteDir = join(projectRoot, ".site");
  await mkdir(siteDir, { recursive: true });

  const target = join(siteDir, "node_modules");
  try {
    await lstat(target);
    // Already exists — leave it alone.
  } catch {
    await symlink(SPOOL_NODE_MODULES, target, "junction");
  }
}

export async function writeWovenFiles(
  projectRoot: string,
  files: Map<string, string>,
): Promise<void> {
  const destDir = join(projectRoot, ".site");

  for (const [relPath, content] of files) {
    const dest = join(destDir, relPath);
    await mkdir(dirname(dest), { recursive: true });
    await writeFile(dest, content, "utf-8");
  }
}

export type VitePressConfigOptions = {
  linkReferences?: boolean;
  passageLocationMap?: PassageLocationMap;
};

export async function writeVitePressConfig(
  projectRoot: string,
  config: SpoolConfig,
  options: VitePressConfigOptions = {},
): Promise<void> {
  const vpDir = join(projectRoot, ".site", ".vitepress");
  await mkdir(vpDir, { recursive: true });

  const vpConfig: Record<string, unknown> = {
    srcDir: ".",
    ...config.site,
  };

  if (!vpConfig.themeConfig) {
    vpConfig.themeConfig = { search: { provider: "local" } };
  }

  const lines: string[] = ["// Generated by spool — do not edit"];

  if (options.linkReferences && options.passageLocationMap) {
    const mapObj: Record<string, { url: string }> = {};
    for (const [key, info] of options.passageLocationMap) {
      mapObj[key] = { url: info.url };
    }
    lines.push(`const passageMap = ${JSON.stringify(mapObj)};`);
    lines.push("");
    lines.push("const spoolLinkTransformer = {");
    lines.push("  postprocess(html) {");
    lines.push(
      // ::SPOOL:: ignore-next
      "    return html.replace(/::SPOOL:: (?:&lt;|&#x3C;)(?:&lt;|&#x3C;)(.+?)(?:#([\\w-]+))?(?:&gt;|>)(?:&gt;|>)/g, (match, file, passage) => {",
    );
    lines.push("      const key = passage ? file + ':' + passage : file + ':';");
    lines.push("      const info = passageMap[key];");
    lines.push("      if (info) {");
    lines.push("        const label = passage ? file + '#' + passage : file;");
    lines.push(
      "        return '<a href=\"' + info.url + '\" class=\"spool-ref\">' + label + '</a>';",
    );
    lines.push("      }");
    lines.push("      return match;");
    lines.push("    });");
    lines.push("  }");
    lines.push("};");
    lines.push("");

    vpConfig.markdown = {
      ...(vpConfig.markdown as Record<string, unknown> | undefined),
      codeTransformers: "__SPOOL_TRANSFORMERS__" as unknown,
    };
  }

  let configJson = JSON.stringify(vpConfig, null, 2);

  if (options.linkReferences && options.passageLocationMap) {
    configJson = configJson.replace('"__SPOOL_TRANSFORMERS__"', "[spoolLinkTransformer]");
  }

  lines.push(`export default ${configJson}`);
  lines.push("");

  await writeFile(join(vpDir, "config.js"), lines.join("\n"), "utf-8");
}

const THEME_INDEX = `\
import DefaultTheme from "vitepress/theme";
import SpoolPassage from "./SpoolPassage.vue";

export default {
  extends: DefaultTheme,
  enhanceApp({ app }) {
    app.component("SpoolPassage", SpoolPassage);
  },
};
`;

const SPOOL_PASSAGE_VUE = `\
<script setup>
import { ref, onMounted, onUnmounted } from "vue";

const props = defineProps({
  anchor: { type: String, default: undefined },
});

const passageEl = ref(null);

function triggerIfTargeted() {
  if (!props.anchor || !passageEl.value) return;
  if (window.location.hash === "#" + props.anchor) {
    const el = passageEl.value;
    el.classList.remove("spool-targeted");
    void el.offsetWidth; // force reflow to restart animation
    el.classList.add("spool-targeted");
  }
}

onMounted(() => {
  triggerIfTargeted();
  window.addEventListener("hashchange", triggerIfTargeted);
});

onUnmounted(() => {
  window.removeEventListener("hashchange", triggerIfTargeted);
});
</script>

<template>
  <div :id="anchor" ref="passageEl" class="spool-passage">
    <slot />
  </div>
</template>

<style scoped>
.spool-passage {
  position: relative;
  border-radius: 4px;
}

.spool-passage.spool-targeted :deep(pre) {
  animation: spool-highlight 600ms ease-out forwards;
}

@keyframes spool-highlight {
  0%, 50% {
    background-color: rgba(255, 220, 50, 0.25);
  }
  100% {
    background-color: transparent;
  }
}
</style>
`;

export async function writeVitePressTheme(projectRoot: string): Promise<void> {
  const themeDir = join(projectRoot, ".site", ".vitepress", "theme");
  await mkdir(themeDir, { recursive: true });
  await writeFile(join(themeDir, "index.ts"), THEME_INDEX, "utf-8");
  await writeFile(join(themeDir, "SpoolPassage.vue"), SPOOL_PASSAGE_VUE, "utf-8");
}

export async function startDevServer(
  siteDir: string,
  port: number,
): Promise<{ port: number; stop(): Promise<void> }> {
  const { createServer } = await import("vitepress");
  const server = await createServer(siteDir, { port });
  await server.listen();
  const addr = server.httpServer?.address();
  const actualPort = typeof addr === "object" && addr !== null ? addr.port : port;
  return {
    port: actualPort,
    async stop() {
      await server.close();
    },
  };
}

export async function buildSite(siteDir: string): Promise<void> {
  const { build } = await import("vitepress");
  await build(siteDir);
}
