import { lstat, mkdir, symlink, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import type { SpoolConfig } from "../../config.ts";

// Spool's own node_modules directory. Projects using spool typically have no
// VitePress/Vue of their own, so we symlink .site/node_modules to spool's copy
// so that VitePress can resolve its dependencies.
//
// Path from source: src/commands/site/vitepress.ts → 4 dirname calls → spool/
// Path from dist:   dist/commands/site/vitepress.js → 4 dirname calls → spool/
const SPOOL_ROOT = dirname(dirname(dirname(dirname(fileURLToPath(import.meta.url)))));
const SPOOL_NODE_MODULES = join(SPOOL_ROOT, "node_modules");

export async function prepareSiteDir(projectRoot: string): Promise<void> {
  const siteDir = join(projectRoot, ".site");
  await mkdir(siteDir, { recursive: true });

  const target = join(siteDir, "node_modules");
  try {
    await lstat(target);
    // Already exists — leave it alone.
  } catch {
    await symlink(SPOOL_NODE_MODULES, target, "junction");
  }
}

export async function writeWovenFiles(
  projectRoot: string,
  files: Map<string, string>,
): Promise<void> {
  const destDir = join(projectRoot, ".site");

  for (const [relPath, content] of files) {
    const dest = join(destDir, relPath);
    await mkdir(dirname(dest), { recursive: true });
    await writeFile(dest, content, "utf-8");
  }
}

export async function writeVitePressConfig(
  projectRoot: string,
  config: SpoolConfig,
): Promise<void> {
  const vpDir = join(projectRoot, ".site", ".vitepress");
  await mkdir(vpDir, { recursive: true });

  const vpConfig: Record<string, unknown> = {
    srcDir: ".",
    ...config.site,
  };

  if (!vpConfig.themeConfig) {
    vpConfig.themeConfig = { search: { provider: "local" } };
  }

  const configSource = [
    "// Generated by spool — do not edit",
    `export default ${JSON.stringify(vpConfig, null, 2)}`,
    "",
  ].join("\n");

  await writeFile(join(vpDir, "config.js"), configSource, "utf-8");
}

export async function startDevServer(
  siteDir: string,
  port: number,
): Promise<{ port: number; stop(): Promise<void> }> {
  const { createServer } = await import("vitepress");
  const server = await createServer(siteDir, { port });
  await server.listen();
  const addr = server.httpServer?.address();
  const actualPort = typeof addr === "object" && addr !== null ? addr.port : port;
  return {
    port: actualPort,
    async stop() {
      await server.close();
    },
  };
}

export async function buildSite(siteDir: string): Promise<void> {
  const { build } = await import("vitepress");
  await build(siteDir);
}
